[book]
authors = ["Justin Bender"]
language = "en"
multilingual = false
src = "src"
title = "ProLUG ğŸ§ Labs Notebook"
description = "Linux ğŸ§ and System skills to get the job"

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/ScriptAlchemist/ProLUG-labs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/ScriptAlchemist/ProLUG-labs/edit/main/{path}"
site-url = "/ProLUG-labs/"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.playground]
editable = true
line-numbers = true

[preprocessor.pagetoc]

