[book]
authors = ["Justin Bender"]
language = "en"
multilingual = false
src = "src"
title = "ProLUG Labs Notebook"
description = "Linux and System skills to get the job"

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/ScriptAlchemist/ProLUG-labs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/ScriptAlchemist/ProLUG-labs/edit/main/{path}"
site-url = "/ProLUG-labs/"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
